name: uncertainty-reasoner
channels:
  - defaults
dependencies:
  - anyio=4.2.0
  - argon2-cffi=21.3.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.0
  - cryptography=41.0.7
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - expat=2.5.0
  - fonttools=4.51.0
  - freetype=2.12.1
  - icu=73.1
  - idna=3.4
 # - intel-openmp=2023.1.0  # Ignored on Mac but OK to leave
  - ipykernel=6.28.0
  - ipython=8.20.0
  - jedi=0.18.1
  - jinja2=3.1.3
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lerc=3.0
  - libclang=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libpng=1.6.39
  - libpq=12.17
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  #- mkl=2023.1.0  # Can optionally remove if not using MKL on Mac
  #- mkl-service=2.4.0
 # - mkl_fft=1.3.8
 # - mkl_random=1.2.4
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - nest-asyncio=1.6.0
  - notebook=7.0.8
  - notebook-shim=0.2.3
  - numexpr=2.8.7
  - numpy=1.26.4
  - openjpeg=2.4.0
  - openpyxl=3.1.2
  - openssl=3.0.13
  - overrides=7.4.0
  - packaging=23.2
  - pandas=2.1.4
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pillow=10.2.0
  - pip=23.3.1
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.12.0
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  #- pywin32  # Remove or comment this line if on macOS/Linux
  #- pywinpty  # Same as above
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - send2trash=1.8.2
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tbb=2021.8.0
